import { Bell, Bot, Check, ChevronRight, ContactRound, MessageCircle, Plus, Sparkles } from "lucide-react";

export function LandingPhone({ view = "dashboard", compact = false }: { view?: "dashboard" | "followups" | "prospect" | "assistant"; compact?: boolean }) {
  return <div className={`lp-phone ${compact ? "lp-phone-compact" : ""}`} aria-label={`Maquette illustrative : ${view === "dashboard" ? "dashboard" : view === "followups" ? "relances du jour" : view === "prospect" ? "fiche prospect" : "assistant IA"}`}>
    <div className="lp-island" /><div className="lp-phone-status"><span>9:41</span><span>••• ▰</span></div>
    <div className="lp-screen">
      <div className="flex items-center justify-between gap-2 border-b border-border pb-4"><span className="flex items-center gap-2 text-xs font-bold"><span className="grid size-6 place-items-center rounded-md bg-primary text-primary-foreground"><Sparkles className="size-3" /></span>MLM Boost AI</span><Bell className="size-4 text-muted-foreground" /></div>
      {view === "dashboard" && <>
        <div className="lp-screen-item mt-5"><span className="text-[10px] text-muted-foreground">TON ESPACE DE TRAVAIL</span><h3 className="mt-1 text-lg font-bold">Chaque jour, un pas de plus.</h3></div>
        <div className="lp-screen-item lp-demo-block mt-4"><span className="text-xs font-semibold">Démarrer en 3 étapes</span><div className="mt-3 flex items-center gap-2 text-[11px]"><Check className="size-4 text-success" />Ajouter ton premier prospect</div><div className="mt-2 flex items-center gap-2 text-[11px]"><Check className="size-4 text-success" />Générer ton premier message</div><div className="mt-2 flex items-center gap-2 text-[11px] text-muted-foreground"><MessageCircle className="size-4 text-primary" />L’envoyer sur WhatsApp</div></div>
        <div className="lp-screen-item mt-4 flex items-center justify-between text-xs font-bold"><span>À relancer aujourd’hui</span><span className="size-6 rounded-md bg-primary/15 p-1 text-center text-primary">2</span></div>
        <DemoContact name="Amina" label="Intéressé" /><DemoContact name="Yannick" label="Discussion" />
      </>}
      {view === "followups" && <><h3 className="mt-6 text-xl font-bold">Les bonnes relances.<br />Au bon moment.</h3><div className="lp-demo-block mt-5"><span className="text-xs font-bold">À relancer aujourd’hui</span><DemoContact name="Amina" label="Aujourd’hui" /><p className="mt-2 text-[11px] text-muted-foreground">Après la présentation de [Produit]</p><span className="mt-4 flex min-h-9 items-center justify-center gap-2 rounded-md bg-success/15 text-[11px] font-bold text-success"><MessageCircle className="size-3" />Envoyer via WhatsApp</span></div><DemoContact name="Yannick" label="2 jours de retard" /><span className="mt-4 block text-center text-[11px] text-primary">Reporter à demain →</span></>}
      {view === "prospect" && <><div className="mt-6 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-primary/15 text-lg font-bold text-primary">A</span><div><h3 className="text-lg font-bold">Amina</h3><span className="text-[11px] text-success">Intéressé · Chaud</span></div></div><span className="mt-5 flex min-h-10 items-center justify-center gap-2 rounded-md bg-primary text-[11px] font-semibold text-primary-foreground"><Sparkles className="size-3" />Suggérer la prochaine action</span><div className="mt-5 grid gap-3">{[["Source", "WhatsApp"], ["Produit d’intérêt", "[Produit]"], ["Objection principale", "Je souhaite en savoir plus"], ["Prochaine relance", "Demain"]].map(([label, value]) => <div key={label} className="border-b border-border pb-2"><span className="text-[10px] text-muted-foreground">{label}</span><p className="mt-1 text-xs">{value}</p></div>)}</div><p className="mt-4 text-[10px] text-muted-foreground">Fiche · Historique</p></>}
      {view === "assistant" && <><span className="mt-6 flex items-center gap-2 text-primary"><Bot className="size-5" /><h3 className="text-lg font-bold">Assistant IA</h3></span><div className="mt-4 grid grid-cols-2 gap-2 text-[10px]">{["Prospection", "Réponse", "Script d’appel", "Post social"].map((m, i) => <span key={m} className={`rounded-md border p-2 ${i === 0 ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}>{m}</span>)}</div><div className="lp-demo-block mt-4 text-[11px] text-muted-foreground">Un message pour Amina, qui souhaite en savoir plus sur [Produit].</div><div className="lp-demo-block mt-3"><span className="flex items-center gap-1 text-[10px] font-semibold text-primary"><Sparkles className="size-3" />TON MESSAGE</span><p className="mt-3 text-xs leading-6">Salut Amina ! Tu voulais en savoir plus sur [Produit]. Qu’est-ce que tu aimerais découvrir en premier ? Je suis là pour répondre à tes questions.</p></div><span className="mt-3 flex min-h-9 items-center justify-center gap-2 rounded-md bg-success/15 text-[11px] font-bold text-success"><MessageCircle className="size-3" />Envoyer via WhatsApp</span></>}
    </div>
    <div className="lp-phone-nav"><ContactRound /><Plus /><Bot /><ChevronRight /></div>
  </div>;
}

function DemoContact({ name, label }: { name: string; label: string }) {
  return <div className="lp-screen-item mt-3 flex min-w-0 items-center gap-2 rounded-md border border-border bg-card/70 p-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-info/15 text-xs font-bold text-info">{name[0]}</span><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{name}</p><p className="mt-1 text-[10px] text-muted-foreground">{label}</p></div><ChevronRight className="size-3 shrink-0 text-primary" /></div>;
}